### PR TITLE
BG1000N - BS1000 compatibility

### PR DESCRIPTION
**Pull request by weigo87**
B1000N00 - B1000N07 should be skipped for BGGO extended night
This means that the order of installation does not matter

### CODE REVIEW

**Comment by Gitjas** [comment]
This is because BGGO inserts these itself already?

**Comment by Gitjas** [comment]
Would it make sense to skip them in BST always?

**Comment by weigo87** [comment]
We leave the indices from 00 - 07 blank with the code, so that the day and night indices remain the same and therefore have no problem with the sequence. If someone installs BS first, 00-07 would already be occupied from BS and so BGGO would overwrite it. (I had this problem before) From the BGGO side, it is much more difficult to implement the search for a free index, as I would have to program it individually for far more than 100 areas. With BGGO, some must be overwritten and some not and therefore I cannot implement it generally.   
It is only used for the BG1000, all other areas of BS start searching at 0.

**Comment by Gitjas** [comment]
OK, then it already considers that they stay unused / free even if BST is the installed first. Gotcha.

**Pull request merged**
